name: Bug Report
description: File a bug report to help us improve!
title: "[Bug]: "
labels: [needs attention, bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! We use this nifty issue form to make it as straight-forward as possible!
  - type: textarea
    id: reproducing
    attributes:
      label: Steps to reproduce
      description: Tell us how we can replicate your issue!
      placeholder: Give us a list of steps to reproduce your issue!
      value: |
        "1. Start the '...'
        2. Run '....'
        3. Look at '....'
        4. Observe the error"
    validations:
      required: true
  - type: input
    id: logs
    attributes:
      label: Logs
      description: Give us a copy of your server log file! We recommend [mclo.gs](https://mclo.gs) which is included and automatically removes IPs and other sensitive stuff!
      placeholder: https://mclo.gs/8FlTowW
    validations:
      required: true
  - type: textarea
    id: os-version
    attributes:
      label: What's your host OS version?
      description: What's your host's OS version (if you're using a Shared Host, say which one aswell/instead!)
      placeholder: |
        On Windows: Output from `systeminfo | findstr /B /C:"OS Name" /C:"OS Version"`
        On Linux: Output from `sudo apt install lsb-release -y & lsb_release -as` (If you're not on a Debian-based distro, you may need to use a different package manager than `apt`!)
        On a Shared Host: Just link us to the one you're using and tell us which plan/hosting customizations (ex. DDoS Protection) you're using!
    validations:
      required: true
  - type: textarea
    id: java-version
    attributes:
      label: Java Version
      description: What's your exact Java version?
      placeholder: Run `java -version` from your Terminal, CMD, or in PowerShell!
    validations:
      required: true
  - type: dropdown
    id: client-version
    attributes:
      label: Client Version
      description: What clientside version are you using? (Make sure your bug happens with Vanilla clients!)
      options:
        - "1.17"
        - "1.17.1"
        - "Something newer than 1.17.1"
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If possible, add [**imgur.com**](https://imgur.com/upload) screenshots to help us understand your problem. **YOU MUST** use [imgur.com](https://imgur.com/upload) and censor out all private/personally identifiable information!
      placeholder: https://imgur.com/upload
  - type: checkboxes
    id: agreements
    attributes:
      label: Agreements
      description: Do you agree to all of the following (and confirm they are all true)?
      multiple: true
      options:
        - label: I'm running my server in online mode (either directly on my backends or on my proxy)
          required: true
        - label: The issue occurs with a fresh, clean install of the repo (or I've forked this repository, published my changes, and linked it under **Additional Information** below)
          required: true
        - label: I've removed all private/personally identifiable information from this report and anything referenced in this report
          required: true
        - label: This isn't a security issue because security issues should be reported following the information in [`SECURITY.md`](https://github.com/GamesROB/documentation/security/policy), **NOT** through GitHub issues
          required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: If you have any other context or relevant information/insight about the problem, put it here.
